### ISSUE TITLE
does not respect valueEncoding: 'json' when using .createReadStream

### ISSUE THREAD

**Issue by austinfrey** [mafintosh/subleveldown#6]
When passing an valueEncoding of `json` to a sublevel instance, it does not appear to respect the encoding when using `createReadStream`. It does however work with the `.get` method. Here's my example code:
```javascript
const level = require('level')
const sub = require('subleveldown')

const db = level('./stream.db')
const jsonDB = sub(db, 'json', {valueEncoding:'json'})

jsonDB.put('foo', {'bar': 'baz'}, (err) => {
  jsonDB.get('foo', (err, val) => {
    console.log('GET',err || val)
    jsonDB.createReadStream().on('data', data => console.log(data))
  })
})
```
with an output of:
```
GET { bar: 'baz' }

events.js:183
      throw er; // Unhandled 'error' event
      ^
EncodingError: Unexpected token o in JSON at position 1
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/level-iterator-stream/index.js:36:28
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/subleveldown/leveldown.js:23:8
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-iterator.js:24:16
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/encoding-down/index.js:114:5
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:24:16
    at /home/austin/projects/proj-hyperlog/hyperlog-rep/node_modules/leveldown/iterator.js:43:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
This is what I was expecting to see:
```
GET { bar: 'baz' }
{ key: 'foo', value: { bar: 'baz' } }
```

Any help appreciated. Thanks

**Comment by ralphtheninja** [comment]
Move `{ valueEncoding: 'json' }` to `level` instead:

```js
const level = require('level')
const sub = require('subleveldown')

const db = level('./stream.db', {valueEncoding:'json'})
const jsonDB = sub(db, 'json')

jsonDB.put('foo', {'bar': 'baz'}, (err) => {
  jsonDB.get('foo', (err, val) => {
    console.log('GET',err || val)
    jsonDB.createReadStream().on('data', data => console.log(data))
  })
})
```

**Comment by austinfrey** [comment]
@ralphtheninja thanks for the tip, is there a way to handle two sublevels, where I want sublevel A to be `json` encoded and sublevel B to be buffers? I believe the docs state that I should be able to pass in the encoding to a sublevel instance correct? but I could be mistaken

**Comment by ralphtheninja** [comment]
@austinfrey I'd have to get back to you on that since I haven't used `subleveldown` with the latest `level` and this use case.

@vweevers Any input?

**Comment by vweevers** [comment]
subleveldown isn't compatible with latest `level(up)` as it expects `levelup` to handle encodings.

**Comment by austinfrey** [comment]
@ralphtheninja @vweevers good to know. thanks to both of you for weighing in
